"""
Django settings for MxOnline project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4bk(+x$j-o40mz$gpuh2xe@@ujh5ne+ypkux4tn^gepq-f(hb-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# DEBUG = False
#
# # 关闭 DEBUG 后必须配置 ALLOWED_HOSTS，否则会报 400 错误
# ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '*']
# Application definition

AUTHENTICATION_BACKENDS = (
    'apps.users.views.CustomBackend',
    # 'django.contrib.auth.backends.ModelBackend',
)

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'users.apps.UsersConfig',
    # 'courses.apps.CoursesConfig',
    # 'organization.apps.OrganizationConfig',
    # 'organization.apps.OperationConfig'
    'users',
    'courses',
    'organization',
    'operation',
    'captcha',
    'pure_pagination',
    'django.forms'
]

# 允许使用全局TEMPLATES配置
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

AUTH_USER_MODEL = 'users.UserProfile'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware'
]

ROOT_URLCONF = 'MxOnline.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',

            ],
        },
    },
]

WSGI_APPLICATION = 'MxOnline.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "mxonline",
        'USER': "root",
        'PASSWORD': "eduvideo890..",
        'HOST': "127.0.0.1",
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

# USE_TZ = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# 1. 静态资源访问前缀
STATIC_URL = '/static/'

# 2. 开发环境静态资源存放目录（你的源代码文件）
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# 3. 生产环境收集静态资源的绝对路径（必须与 STATICFILES_DIRS 区别开）
# 用来在执行 python manage.py collectstatic 命令时
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 邮箱设置
EMAIL_HOST = "smtp.sina.com"
EMAIL_PORT = 465
EMAIL_HOST_USER = "zhixingonline@sina.cn"
EMAIL_HOST_PASSWORD = "316df1591ba6d50a"
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_FROM = EMAIL_HOST_USER

EMAIL_VERIFY_TTL_MINUTES = 30
SITE_URL = 'http://127.0.0.1:8000'

# 授权码
# 316df1591ba6d50a

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

JAZZMIN_SETTINGS = {
    # "language_chooser": True,
    # "show_ui_builder": True,
    # 浏览器页签标题
    'site_title': '知行在线后台管理系统',
    # 登陆时候账号密码上面的标题，如果没有图则显示
    'site_header': '欢迎进入知行在线后台管理系统',
    # 左侧菜单栏的标题
    'site_brand': "知行在线后台管理系统",
    # 登录欢迎语
    'welcome_sign': '欢迎登录知行在线后台系统',
    # 页脚信息
    'copyright': '知行在线后台管理系统',
    # 设置为 False：默认折叠所有 App 分组，点击可展开/收起（关键配置）
    'navigation_expanded': False,
    # 子菜单缩进：加深层级对比，视觉效果更好（可选）
    'sidebar_nav_child_indent': True,

    # 1. 登录成功后，后台左上角显示的主 Logo
    "site_logo": "jazzmin/img/login_logo.jpg",

    # 2. 浏览器标签页图标 (Favicon)
    "site_icon": "jazzmin/img/website_logo.png",

    # 3. 登录页面居中显示的大 Logo
    "login_logo": "jazzmin/img/login_logo.jpg",
    # 左上角 Logo 的 CSS 样式类（针对方形/圆形图标的展示优化）
    "site_logo_classes": "img-circle",
    "custom_css": "css/custom_jazzmin.css",
}
