# Generated by Django 6.0 on 2026-09-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_video_learn_times_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(default='', max_length=500, upload_to='', verbose_name='访问地址'),
        ),
    ]
